#! /bin/sh

# Startups
bash $HOME/.config/bspwm/bin/bspbar.sh &
bash $HOME/.config/bspwm/bin/bspcomp.sh &
xsetroot -cursor_name left_ptr &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
hsetroot -cover /usr/share/backgrounds/at_the_coffeshop.png &
dunst -config ~/.config/bspwm/dunstrc &
pgrep -x sxhkd > /dev/null || sxhkd -c ~/.config/bspwm/sxhkdrc &

# focus with pointer
bspc config focus_follows_pointer false


# border colors basic
bspc config focused_border_color '#a2b1e7'
bspc config normal_border_color '#454875'


bspc monitor -d 1 2 3 4 5 6
# window gap and width
bspc config border_width         3
bspc config window_gap          14

# Defaults
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a code desktop='^2' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Screenkey manage=off
